import './globals.scss';

import StoreProvider from './GlobalStore/StoreProvider.js';

export const metadata = {
    title: 'M U S T H A V E',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
