import './globals.scss';
import StoreProvider from './GlobalStore/StoreProvider.js';

export const metadata = {
    title: 'M U S T H A V E',
    description: 'Premium fashion store - Generated by Hubert Łepski',
    //viewport: 'width=device-width, initial-scale=1',
};

export const viewport = {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
};

export default function RootLayout({ children }) {
    return (
        <html lang='en' suppressHydrationWarning={true}>
            <body>
                <StoreProvider>{children}</StoreProvider>
            </body>
        </html>
    );
}
